# Directory to store the statistics in [string]
statsDir = "/var/log/stats"

[dtn]
# dtnd details
dtndAddress = "127.0.0.1"
dtndPort = 3000

# URI with dtn scheme [string]
remoteNodeId = "dtn://base"

# Bundle lifetime in seconds [int]
lifetime = 5000


[ros]
# Format:
# [topicName, msgType, [profile]]

# Topics to subscribe to
topics = [
    [
        "/detectedImages",
        "sensor_msgs/msg/Image",
    ],
    [
        "/status/position",
        "geometry_msgs/msg/PointStamped",
    ],
    [
        "/status/battery",
        "sensor_msgs/msg/BatteryState",
    ],
    [
        "/status/tempSensor",
        "diagnostic_msgs/msg/DiagnosticArray",
    ],
    [
        "/temperature",
        "sensor_msgs/msg/Temperature",
    ],
    [
        "/humidity",
        "sensor_msgs/msg/RelativeHumidity",
    ],
]
