# Directory to store the statistics in [string]
statsDir = "/var/log/stats"

[dtn]
# dtnd details
dtndAddress = "127.0.0.1"
dtndPort = 3000

# URI with dtn scheme [string]
remoteNodeId = "dtn://robot"

# Bundle lifetime in seconds [int]
lifetime = 5000


[ros]
# Format:
# [topicName, msgType, [profile]]DEBUG

# Topics to publish
pub = [
    [
        "/robot0/detectedImages",
        "sensor_msgs/msg/Image",
        "decompress_tf",
    ],
    [
        "/robot0/status/position",
        "geometry_msgs/msg/PointStamped",
        "decompress",
    ],
    [
        "/robot0/status/battery",
        "sensor_msgs/msg/BatteryState",
        "decompress",
    ],
    [
        "/robot0/status/tempSensor",
        "diagnostic_msgs/msg/DiagnosticArray",
        "decompress",
    ],
    [
        "/robot0/temperature",
        "sensor_msgs/msg/Temperature",
        "sensor0",
    ],
    [
        "/robot0/humidity",
        "sensor_msgs/msg/RelativeHumidity",
        "sensor0",
    ],
    [
        "/robot0/radiation",
        "radiation_msgs/msg/DoseRate",
        "sensor0",
    ],
    [
        "/robot0/atmPressure",
        "sensor_msgs/msg/FluidPressure",
        "sensor0",
    ],
    [
        "/robot1/detectedImages",
        "sensor_msgs/msg/Image",
        "decompress_tf",
    ],
    [
        "/robot1/status/position",
        "geometry_msgs/msg/PointStamped",
        "decompress",
    ],
    [
        "/robot1/status/battery",
        "sensor_msgs/msg/BatteryState",
        "decompress",
    ],
    [
        "/robot1/status/tempSensor",
        "diagnostic_msgs/msg/DiagnosticArray",
        "decompress",
    ],
    [
        "/robot1/temperature",
        "sensor_msgs/msg/Temperature",
        "sensor1",
    ],
    [
        "/robot1/humidity",
        "sensor_msgs/msg/RelativeHumidity",
        "sensor1",
    ],
    [
        "/robot1/radiation",
        "radiation_msgs/msg/DoseRate",
        "sensor1",
    ],
    [
        "/robot1/atmPressure",
        "sensor_msgs/msg/FluidPressure",
        "sensor1",
    ],
    [
        "/robot2/detectedImages",
        "sensor_msgs/msg/Image",
        "decompress_tf",
    ],
    [
        "/robot2/status/position",
        "geometry_msgs/msg/PointStamped",
        "decompress",
    ],
    [
        "/robot2/status/battery",
        "sensor_msgs/msg/BatteryState",
        "decompress",
    ],
    [
        "/robot2/status/tempSensor",
        "diagnostic_msgs/msg/DiagnosticArray",
        "decompress",
    ],
    [
        "/robot2/temperature",
        "sensor_msgs/msg/Temperature",
        "sensor2",
    ],
    [
        "/robot2/humidity",
        "sensor_msgs/msg/RelativeHumidity",
        "sensor2",
    ],
    [
        "/robot2/radiation",
        "radiation_msgs/msg/DoseRate",
        "sensor2",
    ],
    [
        "/robot2/atmPressure",
        "sensor_msgs/msg/FluidPressure",
        "sensor2",
    ],
]

[[profile]]
name = "decompress"
[[profile.module]]
name = "Decompress"
params = []

[[profile]]
name = "decompress_tf"
[[profile.module]]
name = "SplitTF"
params = []

[[profile]]
name = "sensor0"
[[profile.module]]
name = "Decompress"
params = []
[[profile.module]]
name = "Split"
params = ["/robot0/temperature", "/robot0/humidity", "/robot0/radiation", "/robot0/atmPressure"]

[[profile]]
name = "sensor1"
[[profile.module]]
name = "Decompress"
params = []
[[profile.module]]
name = "Split"
params = ["/robot1/temperature", "/robot1/humidity", "/robot1/radiation", "/robot1/atmPressure"]

[[profile]]
name = "sensor2"
[[profile.module]]
name = "Decompress"
params = []
[[profile.module]]
name = "Split"
params = ["/robot2/temperature", "/robot2/humidity", "/robot2/radiation", "/robot2/atmPressure"]
