# Directory to store the statistics in [string]
statsDir = "/var/log/stats"

[dtn]
# dtnd details
dtndAddress = "127.0.0.1"
dtndPort = 3000

# URI with dtn scheme [string]
remoteNodeId = "dtn://robot"

# Bundle lifetime in minutes [int]
lifetime = 5


[ros]
# Format:
# [topicName, msgType]

# Topics to subscribe to
# sub = [
#     ["/temperature", "sensor_msgs/msg/Temperature"],
#     ["/humidity", "sensor_msgs/msg/RelativeHumidity"]
#     ]

# Topics to publish
pub = [
    [
        "/temperature",
        "sensor_msgs/msg/Temperature",
        # "sensors",
    ],
    [
        "/humidity",
        "sensor_msgs/msg/RelativeHumidity",
        # "sensors",
    ],
]

# Services to provide
# servers = [
#     ["/add_two_ints", "example_interfaces/srv/AddTwoInts"]
#     ]

# Services to listen to
# clients = [
#     ["/add_two_ints", "example_interfaces/srv/AddTwoInts"]
#     ]

# optimization profiles
# [[profile]]
# name = "sensors"

# [[profile.module]]
# name = "Logging"
# params = []
