# Directory to store the statistics in [string]
statsDir = "/var/log/stats"

[dtn]
# dtnd details
dtndAddress = "127.0.0.1"
dtndPort = 3000

# URI with dtn scheme [string]
remoteNodeId = "dtn://robot"

# Bundle lifetime in seconds [int]
lifetime = 300


[ros]
# Format:
# [topicName, msgType, [profile]]

# Topics to publish
pub = [
    [
        "/temperature",
        "sensor_msgs/msg/Temperature",
        "decompress",
    ],
    [
        "/detectedImages",
        "sensor_msgs/msg/Image",
        "decompress",
    ],
]

# Topics to subscribe to
# optimization profiles

[[profile]]
name = "decompress"
[[profile.module]]
name = "ImageDecompress"
params = []
[[profile.module]]
name = "Decompress"
params = []
