#!/bin/sh

xrdb $HOME/.Xresources
xsetroot -solid grey -cursor_name left_ptr
lxterminal &
# Allow copy & paste when ClientCutText is set to true on the client side
autocutsel -fork
#x-window-manager &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1
xhost +
(sleep 3 && core-pygui) &
#(sleep 7 && wmctrl -ir $(wmctrl -l | grep CORE | cut -d ' ' -f 1) -b add,maximized_vert,maximized_horz) &
#/etc/X11/Xsession
startlxde &
